blank_issues_enabled: false
contact_links:
  - name: Security report (private)
    url: https://github.com/OWNER/REPO/security/advisories
    about: Please report security vulnerabilities privately via GitHub Security Advisories
  - name: Google VRP
    url: https://bughunters.google.com/
    about: If your finding targets Google products/infrastructure (not this repo), submit through Google VRP