name: "🔒 Security vulnerability"
description: Report a security issue privately (sanitized PoC required)
title: "[Security]: <short summary>"
labels: [security]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Please do not include secrets or sensitive personal data. Share only a minimal PoC and details required to reproduce.

  - type: input
    id: summary
    attributes:
      label: Summary
      placeholder: e.g., Prompt injection in AI endpoint allows data exfiltration
    validations:
      required: true

  - type: dropdown
    id: vulnType
    attributes:
      label: Vulnerability type
      options:
        - XSS / Injection
        - Auth/Z auth bypass
        - RCE / Sandbox escape
        - AI: Prompt injection (direct)
        - AI: Prompt injection (indirect)
        - AI: Model manipulation / jailbreak
        - AI: Data exfiltration via tools
        - AI: Safety bypass (policy evasion)
        - SSRF / CSRF / Clickjacking
        - Sensitive data exposure
        - Other
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      placeholder: OS, runtime, app version, API base, model version (e.g., Gemini 2.5)
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Reproduction steps
      description: Numbered steps from a clean state
      placeholder: |
        1. Authenticate as test user
        2. Send request (include full request)
        3. Observe response
    validations:
      required: true

  - type: textarea
    id: poc
    attributes:
      label: Minimal PoC (sanitized)
      description: Paste minimal PoC inline (no external links).
      render: bash
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact analysis
      placeholder: Data exfiltration scope, privilege needed, user interaction, blast radius
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity (self-assessed)
      options:
        - S0 Critical
        - S1 High
        - S2 Medium
        - S3 Low
        - S4 Informational
    validations:
      required: true

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested remediation
      placeholder: Short recommendation(s)

  - type: textarea
    id: notes
    attributes:
      label: Notes / references
      placeholder: Additional context, prior art, related issues