"use client"

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from "recharts"
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar"
import { Badge } from "@/components/ui/badge"

const staffPerformanceData = [
  { name: "Mike Johnson", revenue: 12450, appointments: 89, rating: 4.9, efficiency: 92 },
  { name: "Sarah Davis", revenue: 11200, appointments: 76, rating: 4.8, efficiency: 88 },
  { name: "Alex Rodriguez", revenue: 8900, appointments: 67, rating: 4.6, efficiency: 85 },
]

const weeklyPerformanceData = [
  { week: "Week 1", mike: 2800, sarah: 2600, alex: 2100 },
  { week: "Week 2", mike: 3200, sarah: 2900, alex: 2300 },
  { week: "Week 3", mike: 3100, sarah: 2800, alex: 2200 },
  { week: "Week 4", mike: 3350, sarah: 2900, alex: 2300 },
]

interface StaffPerformanceProps {
  timeframe: string
}

export function StaffPerformance({ timeframe }: StaffPerformanceProps) {
  return (
    <div className="space-y-4">
      <Card>
        <CardHeader>
          <CardTitle>Weekly Performance Comparison</CardTitle>
          <CardDescription>Revenue generated by each staff member</CardDescription>
        </CardHeader>
        <CardContent>
          <ResponsiveContainer width="100%" height={300}>
            <BarChart data={weeklyPerformanceData}>
              <CartesianGrid strokeDasharray="3 3" />
              <XAxis dataKey="week" />
              <YAxis />
              <Tooltip formatter={(value) => [`$${value}`, ""]} />
              <Bar dataKey="mike" fill="hsl(var(--chart-1))" name="Mike Johnson" />
              <Bar dataKey="sarah" fill="hsl(var(--chart-2))" name="Sarah Davis" />
              <Bar dataKey="alex" fill="hsl(var(--chart-3))" name="Alex Rodriguez" />
            </BarChart>
          </ResponsiveContainer>
        </CardContent>
      </Card>

      <div className="grid gap-4 md:grid-cols-3">
        {staffPerformanceData.map((staff) => (
          <Card key={staff.name}>
            <CardContent className="p-4">
              <div className="flex items-center gap-3 mb-4">
                <Avatar>
                  <AvatarImage src={`/staff-${staff.name.toLowerCase().replace(" ", "-")}.jpg`} />
                  <AvatarFallback>
                    {staff.name
                      .split(" ")
                      .map((n) => n[0])
                      .join("")}
                  </AvatarFallback>
                </Avatar>
                <div>
                  <h3 className="font-semibold">{staff.name}</h3>
                  <Badge variant="secondary">Barber</Badge>
                </div>
              </div>

              <div className="space-y-3">
                <div className="flex justify-between">
                  <span className="text-sm text-muted-foreground">Revenue:</span>
                  <span className="font-medium">${staff.revenue.toLocaleString()}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-sm text-muted-foreground">Appointments:</span>
                  <span className="font-medium">{staff.appointments}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-sm text-muted-foreground">Rating:</span>
                  <span className="font-medium flex items-center gap-1">⭐ {staff.rating}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-sm text-muted-foreground">Efficiency:</span>
                  <span className="font-medium">{staff.efficiency}%</span>
                </div>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  )
}
