name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

# Implement concurrency control to prevent multiple runs from interfering
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Limit permissions to minimum required (principle of least privilege)
permissions:
  contents: read
  security-events: write
  pull-requests: write

jobs:
  test-and-build:
    runs-on: ubuntu-22.04

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: modernmen_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install --no-cache

      - name: Run linting
        run: npm run lint

      - name: Type checking
        run: npx tsc --noEmit

      - name: Run unit tests
        run: npm run test:unit
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/modernmen_test

      - name: Run integration tests
        run: npm run test:integration
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/modernmen_test

      - name: Generate code coverage
        run: npm run test:coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage/lcov.info
          fail_ci_if_error: false

      - name: Build application
        run: npm run build
        env:
          NEXT_PUBLIC_APP_URL: http://localhost:3000
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/modernmen_test

      - name: Run security audit
        run: npm run security:audit

  e2e-tests:
    needs: test-and-build
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install --no-cache

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run E2E tests
        run: npm run test:e2e
        env:
          NEXT_PUBLIC_APP_URL: http://localhost:3000

  deploy-staging:
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install --no-cache

      - name: Build application
        run: npm run build

      - name: Deploy to Vercel
        run: npx vercel --prod=false --yes
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          NEXT_PUBLIC_APP_URL: ${{ secrets.STAGING_APP_URL }}
          DATABASE_URL: ${{ secrets.STAGING_DATABASE_URL }}
          PAYLOAD_SECRET: ${{ secrets.PAYLOAD_SECRET }}

  deploy-production:
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install --no-cache

      - name: Build application
        run: npm run build

      - name: Deploy to Vercel
        run: npx vercel --prod=true --yes
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          NEXT_PUBLIC_APP_URL: ${{ secrets.PRODUCTION_APP_URL }}
          DATABASE_URL: ${{ secrets.PRODUCTION_DATABASE_URL }}
          PAYLOAD_SECRET: ${{ secrets.PAYLOAD_SECRET }}

  security-scan:
    runs-on: ubuntu-22.04
    if: github.event_name == 'pull_request'
    permissions:
      security-events: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

  bundle-analysis:
    needs: test-and-build
    runs-on: ubuntu-22.04
    if: github.event_name == 'pull_request'
    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install --no-cache

      - name: Build for analysis
        run: npm run build

      - name: Analyze bundle size
        run: npx @next/bundle-analyzer

      - name: Comment PR with bundle analysis
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '📦 Bundle analysis completed. Check the logs for details.'
            })

  ai-code-review:
    runs-on: ubuntu-22.04
    if: github.event_name == 'pull_request'
    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Vercel AI Code Review
        uses: vercel/ai-action@v2.1.0
        with:
          api-key: ${{ secrets.OPENAI_API_KEY }}
          prompt: |
            You are an expert code reviewer. Analyze the changes in this pull request and provide:

            1. **Summary**: Brief overview of what the PR does
            2. **Code Quality**: Assess code quality, best practices, and potential improvements
            3. **Security**: Check for security vulnerabilities or concerns
            4. **Performance**: Identify potential performance issues
            5. **Testing**: Review test coverage and quality
            6. **Documentation**: Check if documentation needs updates

            Focus on the most important issues and provide actionable feedback.
            Be constructive and specific in your recommendations.

            Files changed in this PR:
            ${{ github.event.pull_request.changed_files }}

            Base branch: ${{ github.base_ref }}
            Head branch: ${{ github.head_ref }}
          model: gpt-4-turbo-preview

      - name: Comment PR with AI Review
        uses: actions/github-script@v7
        if: success()
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🤖 **AI Code Review Complete**\n\nThe AI has analyzed your pull request and provided feedback. Check the workflow logs for detailed recommendations.'
            })