name: Fuzz (Atheris)

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  atheris:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Install fuzz requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-fuzz.txt

      - name: Run schema-generator fuzzer (sanity)
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          python -m atheris fuzz/schema_generator_fuzz.py -only_ascii=1 -runs=50000

      - name: Run supabase-schema-generator fuzzer (sanity)
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          python -m atheris fuzz/supabase_schema_generator_fuzz.py -only_ascii=1 -runs=50000

