// Barber Components Index
export { BarberGallery as Gallery } from './Gallery'
export { BarberTestimonial as Testimonial } from './Testimonial'
export type { Testimonial } from './Testimonial'
export { AboutUs } from './AboutUs'
export { AppointmentForm } from './AppointmentForm'
export { default as BarberProfile } from './BarberProfile'
export { BlogPostCard } from './BlogPostCard'
export { ContactInfo } from './ContactInfo'
export { FAQAccordion } from './FAQAccordion'
export { Footer } from './Footer'
export { Header } from './Header'
export { HeroSection } from './HeroSection'
export { MapEmbed } from './MapEmbed'
export { PricingTable } from './PricingTable'
export { ServiceCard } from './ServiceCard'
export { SocialMediaLinks } from './SocialMediaLinks'
export { TeamMember } from './TeamMember'
